project:
  type: website
  output-dir: docs

  preview:
    port: 5555
    browser: true
    watch-inputs: true
    navigate: true

  render:
    - "*.qmd"
    - "*.md"
    - "!manuals/"
    - "!manuals/**"

  resources:
    - "files/**"
    - ".htaccess"

freeze: auto

bibliography: files/bib/references.bib
csl: files/bib/chicago-author-date.csl

pagetitle: "{{< meta title >}} | Kai Cooper"
author-meta: "Kai Cooper"

website:
  title: "Kai Cooper"
  description: "Kai Cooper is a PhD student at Wharton studying causal inference in theory and application."
  site-url: "https://krdcooper.com"
  navbar:
    pinned: true
    left:
      - text: "About"
        href: "index.qmd"
      - text: "CV"
        href: "cv/index.qmd"
      - text: "Intuition"
        href: "intuition/index.qmd"
      - text: "Research"
        href: "research/index.qmd"
      - text: "Teaching"
        href: "teaching/index.qmd"
      - text: "Talks"
        href: "talks/index.qmd"
    right:
      - text: "{{< iconify bi envelope size=1.1em title='E-mail' >}}"
        href: "mailto:kaicoop@wharton.upenn.edu"
      - text: "{{< iconify bi linkedin size=1.1em title='LinkedIn' >}}"
        href: "https://www.linkedin.com/in/kaicoop-phd/"
      - text: "{{< iconify fa6-brands bluesky size=1.1em title='Bluesky' >}}"
        href: "https://bsky.app/profile/kaicoop.bsky.social"
        rel: me

  page-footer:
    left: |
      <span class="faux-block">{{< fa regular copyright >}} {{< var years >}} Kai Cooper</span>
      <span class="faux-block">PhD student, Operations, Information and Decisions, The Wharton School.</span>
    center: |
      <span class="faux-block">{{< fa brands orcid >}} <strong>ORCID</strong> [{{< var orcid >}}](https://orcid.org/{{< var orcid >}})</span>
    right: |
      <span class="faux-block">Built with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>
      <span class="faux-block">[View Andrew Heiss's source at {{< fa brands github >}} GitHub]({{< var github-url >}})</span>

format:
  html:
    theme:
      - html/ath.scss
    grid:
      body-width: 900px
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai
