project:
  type: website
  output-dir: docs
  preview:
    port: 5566
    browser: false

pagetitle: "{{< meta title >}} | Kai Cooper"
author-meta: "Kai Cooper"

website:
  title: "Kai Cooper"
  description: "Kai Cooper is a PhD student at Wharton studying causal inference in theory and application."
  site-url: "https://krdcooper.com"
  navbar: false

format:
  html:
    theme:
      - styles.scss
    toc: false
    anchor-sections: true
    title-block-banner: false
    page-layout: full
